### ISSUE TITLE
Processa pagina intera non salva l'articolo

### ISSUE THREAD

**Issue by megalux** [faberyx/corriere#38]
In gestione edizioni se si processa la pagina intera l'articolo generato viene visualizzato correttamente, se poi si esce dalla pagina (sia salvando sia non salvando) l'articolo scompare, tipo manca commit

**Comment by faberyx** [comment]
su che edizione/pagina? ho fatto delle prove e non mi succede

**Comment by megalux** [comment]
boh effettivamente adesso funziona...ieri abbiamo fatto n prove su diverse pagine e dava lo stesso problema. Cmq funge, chiudo la issue
