### ISSUE TITLE
Exception su alcuni articoli

### ISSUE THREAD

**Issue by megalux** [faberyx/corriere#46]
Aprendo alcuni articoli da "Review Articoli" oppure da "Gestione Edizioni" -> Seleziono la pagina e vado sul tab "articoli pagina" l'applicazione va in errore 500.

Articoli affetti:
PrimaComunicazione N. 457 giovedì 01 gennaio 2015 - Pagina 1, provare ad aprire i 2 articoli senza titolo.
http://95.110.171.199/article/378/0/1
http://95.110.171.199/article/379/0/1

![image](https://cloud.githubusercontent.com/assets/10223017/6188052/ef103ea4-b38d-11e4-9044-043ddc2c45b8.png)

**Comment by faberyx** [comment]
sono gli articoli che erano stati creati e aveva dato errore di permesso nelle cartelle, forse andrebbero cancellati in automatico

**Comment by megalux** [comment]
OK, chiudo la issue.
Più che fare in modo di cancellare in automatico questi articoli bisogna risolvere il problema dei permessi. Ma ad es. lanciare uno script che riassegna i diritti ogni volta che l'utente fa import?
